version: '3.4'

services:
  sql-server:
    container_name: sql_server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
      - "1435:1433"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "S3cur3P@ssW0rd!"
    volumes: 
      - sqldataca:/var/opt/mssql 
    networks: 
      - my_networkca
    restart: on-failure

  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=sql_server;Database=MyClothesCAA;Persist Security Info=True;User ID=SA;Password=S3cur3P@ssW0rd!;MultipleActiveResultSets=true"
    ports: 
      - "5005:80"
    networks: 
      - my_networkca
    depends_on:
      - sql-server
    restart: on-failure

networks:
  my_networkca:

volumes:
  sqldataca: